### ISSUE TITLE
Common problem when adding user commands

### ISSUE THREAD

**Issue by Tatsujinichi** [mage/mage#103]
Maybe we should write somewhere explicitly that you need to restart the Watch when adding user commands? Myself and others have gotten stuck on this.

**Comment by stelcheck** [comment]
If you are using `mage-console` and are referring to its watch feature, then this should be reported on the `mage-console` repository https://github.com/mage/mage-console.

Could you also please describe the problem itself? Why is adding a user command an issue?

**Comment by Tatsujinichi** [comment]
moving issue to mage-temples
