### ISSUE TITLE
Cryptic error if you haven't run npm run archivist-create

### ISSUE THREAD

**Issue by Tatsujinichi** [mage/mage#104]
The error seems to come from auth in the mage server console window, and invalidusername on client side.

**Comment by stelcheck** [comment]
Please provide more details than this, including:

  1. Log output
  2. Specifically what you think is weird about it.
  3. Optionally, any suggestions on how we could fix this issue.

**Comment by stelcheck** [comment]
After discussion with @Tatsujinichi - the issue boils down to MAGE not telling you that you had to run archivist before running it.

TBH while I can hardly think of a way to solve this one, I have been frustrated a bit by this in the past (also by the fact that you need to both create and migrate, which may seem a bit strange).

So no solutions for now, but I suggest we keep this issue around to see what we can do about it in the future.

**Comment by ronkorving** [comment]
I think one thing that can be done is to make "create" *imply* "migrate" (not the other way around though).

**Comment by stelcheck** [comment]
That would be nice. From there  not sure how we could warn the user that running it would be needed... at the very least, it appears like it would ne a lot of untrustworthy code.

**Comment by nullorvoid** [comment]
Can Mage know from the config if we have vaults that are supposed to be there and are not? On start up say throw a 'VaultException' vault unreachable or something similar?

**Comment by stelcheck** [comment]
It could. But I suspect it would take a fair bit of code to make this happen. Either:

  1. Each vault backend throws that error if a db/bucket/whatever is not found
  2. Each vault expose some `exists` method, which would be called during initialization and which some part of the core initialization code would be able to throw an error on.

**Comment by stelcheck** [comment]
Removed the milestone for now. This is taking more time to solve, unfortunately, but it is not forgotten.
