### ISSUE TITLE
streaming usercommands

### ISSUE THREAD

**Issue by stelcheck** [mage/mage#116]
## Description

For "hard" real-time games, making one user command call for every action is likely heavier than it needs to be. We also have an issue with detecting the presence of users (we can detect session validity, but cannot see the actual connectivity status of a given user at a specific given time).

To solve these types of issue, I believe it would be nice to provide streaming user commands, which would receive a stream of data instead of a single set of data. They would:

## Features

  1. Be considered as persistent connections
  2. Provide a streaming endpoint to clients
  3. Receive an initial request, with data
  4. Receive a stream object
  5. Client will send additional data asynchronously on this stream, and server will read that data from the stream object
  6. Stream object will both emit 'error's and 'close' events; server will also emit 'data'
  7. Both client and server will be capable of closing the stream.

## API

```javascript
const gameModule = require('../')

exports.acl = ['*']

exports.execute = async function (state, stream, username, password) {
  if (username !== 'bob' || password !== 'the builder') {
     // Will trigger an 'error' event on the client 
     throw new Error('authentication error')
  }

  // Join the game
  const match = gameModule.startMatch(state)

  // Receive stream data
  stream.on('data', (data) => match.executeAction(data))

  // Will execute if the client closes the connection
  stream.on('end', () => match.abort())

  // Close the stream once the game is over
  match.on('end' => stream.close())
}
```

## Architecture

The client would send a long-running HTTP request. It would keep writing data on this request to stream data; each data messages would be sent as serialized line-separated JSON. The server would read each line, JSON.parse, and push them on the stream object.

### HTTP Server

The HTTP server would need to be made aware of the nature of the call; it would then need to remove timeouts and warnings usually set on long-running requests. It would also need to stream data instead of doing a full read and write.

Since I believe the command center register paths and call types, this could likely be solved by adding another route type that will specifically be used by streaming user commands.

### Command center

The command center would need to differentiate between non-streaming and streaming user commands. This should be relatively simple to do.

## Potential benefits

I believe the following types of modules would become easier to write should this kind of API be made available.

  1. Presence: determining the connectivity status of a given user (potentially across multiple devices)
  2. Lobby/chat
  3. Client logging: receiving logs from a client in real time
  4. Gamepad: streaming controller inputs from the client, and interpreting them server-side (and either forward to a remote console or stream back game state updates through msgStream)

cc @ronkorving @AlmirKadric @christopherobin @nullorvoid

**Comment by nullorvoid** [comment]
Would you be able to define a list of expected events for each 'stream' usercommand?

Could I write
```js
// Receive stream data for specific command
stream.on('shoot', (shootData) => match.playerShoot(shootData));
stream.on('jump', (jumpData) => match.jump(jumpData));
```
Or something similar?

Would I be able to use binary and set my expected message size per message expected? Could this be used to support binary messages?

Something like (really not a good API but you should get the idea, it would be better in a config file)
```js
stream.setMessage('jump', 0b1111 , 32) // String Id, Binary code, Length of message
stream.on('jump', (data) => match.jump(data));
```

**Comment by stelcheck** [comment]
We could make this emit an event instead of just plain 'data', yes. However, doing so means we need to stick to JSON for serialization/deserialization, something we may not always want.

Which sort of answers your second question, in a way; we *could*, but then would need to enforce a protocol.

Now, msgStream already enforces JSON for returning data anyway, so maybe we can just settle on JSON, but I think we would close ourselves to some nice opportunities by doing so.

With that in mind, I would suggest the following:

  1. Provide a default protocol and deserialization based on JSON; when using it, you may `stream.on('eventName')`
  2. Add `stream.setRaw()` call, which can be used to turn off the protocol overall. From there. you would be able to use whatever you wish by listening to `.on('data')` events.
  3. Add a `stream.setDeserializer` call, which would allow providing your own deserializer
  4. If needed, write the logic for custom protocols in external or third-party modules

If this all works well, we could eventually expand this approach to all transmissions handled by MAGE, which I think could be a very nice future improvement.

**Comment by stelcheck** [comment]
Reviewed MAGE's current code quickly; so far, everything mentioned so far should be implementable. The only issue I can see so far would be with this line:

https://github.com/mage/mage/blob/master/lib/commandCenter/httpBatchHandler.js#L427

Namely, routing. In short, we will likely want to avoid batching of stream user commands. Connectivity detection might not work well with batching, but most importantly we will not want to hold non-streaming user command's responses from being returned by streaming user commands.

So implementation-wise, we will need to either:

  1. Set a separate path for streaming user commands
  2. Have batching bork out if streaming user commands are mixed with non-streaming

I believe the first option would be preferable.

**Comment by ronkorving** [comment]
I'm a big fan of doing something in this area. But I must share some concerns first (nothing insurmountable :)).

For example, I'm definitely not in favor of having a protocol being toggleable. We should either embrace it, or not implement it at all and leave that to the user. Having both might increase complexity quite tremendously (not just on the server side). I would opt for simple (whichever option we choose).

I'm also concerned about connection limits on non-HTTP/2 *browsers*. Connection limits per domain are a real thing, and using streams adds at least one to the already existing 2, *on the same domain*. I think the solution to this (order of implementation does not matter to me) is to bundle all communication over a single HTTP pipe. Make it all virtual.

**Comment by stelcheck** [comment]
> For example, I'm definitely not in favor of having a protocol being toggleable. We should either embrace it, or not implement it at all and leave that to the user.

Agreed. To rephrase, the protocol should be fixed, but serialization/deserialization would benefit from being customizable.

>  Connection limits per domain are a real thing, and using streams adds at least one to the already existing 2, on the same domain.

Indeed, browsers will have anywhere between 3 to 6 max connections *per host* (not sure if per domain?)
Perhaps the most scalable solution would indeed be to have a single connection for client streams - or even better, repurpose the msgStream so as to send client stream data while its waiting for data back from the server? The latter would have the advantage of making client streams follow the same config as msgStream, so you would be able to use websocket, shortpolling, longpolling.

**Comment by ronkorving** [comment]
Yeah, I think repurposing msgStream for this is most realistic.

**Comment by stelcheck** [comment]
Closing. This would be too much work to implement directly in MAGE at this time; will re-open if a new opportunity arises.
