### ISSUE TITLE
state: flushing known data

### ISSUE THREAD

**Issue by stelcheck** [mage/mage#129]
`state` caches data it has read and modified. This works well for requests, but may be less than ideal when dealing with persistent states. For instance, I may have a global state on my module, which I would use for reading data off the database. 

Right now, it seems most of those cases deal with that by creating a state on demand, then closing it after use. But I think it would make sense to have an API to allow developers to flush the state's cache without closing it.

cc @ronkorving

**Comment by christopherobin** [comment]
I believe it can already be done with [`state.archivist.clearCache()`](https://github.com/mage/mage/blob/master/lib/archivist/index.js#L201-L203) ?

**Comment by stelcheck** [comment]
Oh, you are right, I had missed that.

**Comment by christopherobin** [comment]
It seems to be missing from the `mage.ts` definitions, might be useful to add it there and we could use this issue to track that change.

**Comment by stelcheck** [comment]
Indeed. Let me see what I can do about that.
