### ISSUE TITLE
RFC: MageError class(es)

### ISSUE THREAD

**Issue by stelcheck** [mage/mage#135]
In async user commands, throw errors will either return `error.code` or `error.message`. But when I throw right now, I often do:

```javascript
throw new Error('Invalid request, partner set deck')
```

We should probably promote something like:

```javascript
throw new MageError({
  code: SomeEnumOrMap.ErrorCode,
  message: 'Something bery bery baaad happened',
  details: {
    some,
    request,
    data
  }
})
```

This would:

  1. Encourage developers to set explicit error codes which can then be shared with the client (and which the client should be able to react to)
  2. Still log the message
  3. Attach error-related data with the error instead of having to log those separately
  4. Provide a base class to extend:

> lib/consts/errors.ts

```typescript
import { MageError } from 'mage'

// throw new QueryError(typedDetails)
export QueryError extends MageError<IQueryDetails> {
  public code = 'query_error'
  public message = 'Query failed unexpectedly'
}
```

**Comment by christopherobin** [comment]
Would the data be shared with the client? I could think of a couple cases where the error needs to come with some contextual data on the client.

```typescript
throw new MageError({
  code: GameEnum.NotEnoughBP,
  // need a better name
  contextual_data: {
    game_id: game.id,
    required: game.bp,
    current: user.bp
  },
  message: `User didn't have enough battle points to start a game`,
  details: {
    user: user.id,
    game: game.id,
    required: game.bp,
    current: user.bp,
    some_private_data,
    that_the_client_shouldnt_know
  }
})
```

**Comment by stelcheck** [comment]
That would be great, but it would require that errors be allowed to be of other types than ‘string` or `null`. I am not against that, but maybe @ronkoving can provide some input on that subject.

**Comment by ronkorving** [comment]
This has been on my mind a lot lately, and some of the challenges I foresee (that I literally wrote today :D) you can read at https://github.com/nodejs/CTC/issues/173 (please try not to create noise in that thread, it's for the CTC group and collaborators).

So some notes regarding your suggestion:

- This is quite similar to [VError](https://www.npmjs.com/package/verror) (have a look).
- What about assertion libraries? I think it would be very useful for any blessed error class to have an accompanying assertion library that can throw the right class of error, *with* an error code.
- JavaScript's error classes are globally accessible, are you suggesting making this class global too, or use a require statement in every module? I assume the latter, but that *may* have an impact on how people approach it (one require statement vs. zero *is* a barrier to usage).

**Comment by stelcheck** [comment]
> This is quite similar to verror (really, have a look).

About VError - we *could* make errors chainable indeed, but this is not something I had in mind when opening this request. Still, worth considering.

> What about assertion libraries?

Sounds like a good idea, although it really is syntactic sugar for `if (fails) throw` in the end. So we would need to make sure we really get the APIs right should we create them.

> I assume the latter, but that may have an impact on how people approach it (one require statement vs. zero is a barrier to usage).

By that logic, `mage` should be available globally, I suppose... I am not a big fan of that. I am not sure exposing globally would reduce the barrier to usage in any way, TBH. Devs will use it, or they won't.

**Comment by ronkorving** [comment]
The last point is the least important. But to clarify... By that logic `mage` should not be available globally. My only concern is that *because* there are error classes available globally *and* we already use them today, using something that takes extra effort may cause inconsistent use. People need the discipline to do it right (although you may be able to enforce it with ESLint by banning `Error`, `TypeError`, `RangeError`).

**Comment by stelcheck** [comment]
Thought about this one, and in the end, I'd still prefer to have it required - at least for now. Allowing it globally could always be added in a later release if we get feedback pointing in such direction.

**Comment by ronkorving** [comment]
I've been thinking about it a bit more too. Unrelated to your last comment, but here's something I've been thinking.

I believe users of MAGE are best served with 3 types of error classes:

- programmer error (eg. "this should never happen")
- system error (eg. DB failure)
- user error (eg. "not enough coins")

I think every error that could ever happen on a server will fall exactly into one of these 3 categories, and I think it would help to be able to make that distinction very clear.

```js
throw new ProgrammerError(`Cannot divide by zero`, { some: 'verbose', data: '' });
throw new SystemError(`Archivist get() operation failed`, { some: 'verbose', data: '' });
throw new UserError('insufficientSc', userId);
```

From these categories, logging-level (slash escalation-level) can also very often be decided quite easily I think.

For example, a user error doesn't need human readable text. It just needs a code, and perhaps a user ID. It shouldn't be logged at a high level, it's just informational, but the code does need to finds its way to the client.

Programmer and System errors are way more alarming, but don't need special error codes to travel to the client. They're by default basically "internal server error" (like 500) as far as the client is concerned. We could however add a level argument to the error constructor, which could be overridden very easily.

```js
throw new SystemError(`Archivist get() operation failed`, 'alert', { some: 'verbose', data: '' });
```

**Comment by stelcheck** [comment]
The way I was thinking about it, having a base Error class would allow us to move in that direction.

Obviously, we could use this internally moving forward, after defining an error system that makes sense. As far as user errors are concerned, I think a base class would be sufficient for developers themselves to implement what they would consider being a sane error management strategy.
