### ISSUE TITLE
Switch from `node-uuid` to `uuid`

### ISSUE THREAD

**Issue by Brunni132** [mage/mage#16]
The `node-uuid` module is deprecated and has been replaced by `uuid`.
https://www.npmjs.com/package/node-uuid

We should ensure that the API is compatible for our needs and make the transition.

**Comment by ronkorving** [comment]
The API is compatible with our needs, I already use it on projects in place of node-uuid 👍  We should make the transition.

**Comment by ronkorving** [comment]
Superseded by #21, closing this issue.
