### ISSUE TITLE
Archivist retry

### ISSUE THREAD

**Issue by ronkorving** [mage/mage#162]
Should we add retry logic on write failures or do we just want to rely on multi-vault set ups taking care of these issues? Retries do have to be very carefully managed or they can take down an already unstable system.

Thoughts?

**Comment by stelcheck** [comment]
Retries could be nice, since I do not know many use-cases of multi-vaults. We could have a sane default (3 seems reasonable) configurable over an option object for each mutation operations.

**Comment by stelcheck** [comment]
Thought about this one further: I don't see why we would have that built-in. Failing early and letting retry logic be implemented in user-land makes much more sense to me, regardless of multi-vault.

**Comment by ronkorving** [comment]
How would you do that in user-land? All you have access to is `distribute`, and it doesn't make sense to redistribute 20 operations if only 1 of them failed. Now arguably we should call `vaultValue.resetOperation()` on every vault value that successfully gets distributed, after which we could re-distribute safely any values that remain undistributed. Then a userland retry on distribute would be possible. But still tricky I would say, given that most `archivist.distribute()` calls originate in command center, not userland.

**Comment by stelcheck** [comment]
No, I think you are correct.

I guess the question is, should we have an internal API or should we let developers manually distribute what they wish to retry? Arguably we would not want to retry at all on some error cases.

**Comment by ronkorving** [comment]
That's the first question that needs answering then I guess. Is there a single logic that always applies? eg: the database may have a set of errors that imply that retrying is a good idea, and other errors that imply it's a bad idea. If there's a clear distinction, that may be the best trigger for retrying or not (rather than user-choice and making the user look at 50 different error types to make up their mind). Compare that to how (to the best of my knowledge) with HTTP all 5xx errors *can* be worth a retry, 4xx errors you *should* not retry.

If no such distinction can be made, then unfortunately we would have to move the decision-making responsibility to the user. Ideally we shouldn't, because I think error complexity is a pain, and different databases have different sets of errors.

Are there cases where you would never want to retry even if the database indicates a retry is perfectly valid? Do we care enough about these cases to expose it to the user through API?

**Comment by stelcheck** [comment]
If user-land complexity is a pain, I see no reason why not relieving that pain by making a user-land module dealing with these issues. I feel it would be less risky than trying to get this into the internals of MAGE and having to explain to developers that retries happen by default. 

In the end, I may want only one mutation to retry, for instance - no all of them. The only thing we *could* perhaps consider is emitting an `error` on the state when distribute fail... maybe.

**Comment by ronkorving** [comment]
I think listening for an error is hard to act on, as it's not part of an asynchronous flow. What I was trying to get to above was:

Perhaps it makes sense to let the vaults decide if the operation *can* be retried. Based on that, we can go a few directions. Auto-retry in archivist, or leave it to the user (somehow). I prefer auto-retry if we can get away with it. A big "if", I admit.

**Comment by stelcheck** [comment]
I would imagine that retry logic has more to do with user land logic than vault backend behavior. I may want to retry some operations, but not others. 

We could make it into an option on operations perhaps. Then we would need to introduce API changes to mutation ops, which I believe do not take options at the moment.

That said, if we figured out an API for error management instead, we could then allow for a much more fine grained behavior; for instance, we could allow for interruption, retry or application-level rollback of all ops in the state of we found just the right API to do error handling.

**Comment by ronkorving** [comment]
It could be topic configuration. I think this is the kind of thing you would want to configure per topic. Per operation seems like overkill to me. Doing it through topic configuration also solves the whole "where in userland" problem, since it'll happen during all distribute() operations.

**Comment by stelcheck** [comment]
We might want to discuss this one in person, but I am concerned configuration-based would ultimately yield sufficient control over the workflow. Or at least we'd sort of miss the opportunity to allow developers to implement their own error recovery mechanism.

Perhaps something with a callback would make sense? I'll try to come up with some pseudo-code at some point to demonstrate what I have in mind.

**Comment by stelcheck** [comment]
```javascript
state.archivist.on('error', function (state, operation, cb) {
  // Retry
  return operation.retry(cb)

  // application-level rollback
  state.archivist.clear()
  state.archivist.set(...) // Reset data back to what it was
  state.archivist.distribute(cb)

  // Manually return an error
  return cb(new Error(...))
})
```

One issue I see with this API is that rollbacking or altering msgStream events wouldn't be simple.

**Comment by ronkorving** [comment]
Oh, I like `operation.retry` :)

I would argue that the example above may be easier to implement as:

```
mage.core.archivist.on('error', function (state, operation, cb) {
```

I don't think it would make a ton of sense to set this up on every state object, which is also harder to do because I would have to remember to add something to every user command. There may be ways around it, but MAGE out of the box should make it easy I think. Also, I don't know if having control on a *per state* level would actually help. Besides, you can always pass hints on the state by calling `state.data.retries = 0;` if you wanted to let this error-handler know something about how you want things to be handled.

**Comment by stelcheck** [comment]
Then again you might not want to retry *everything*, or at least not in the same way. That, and plugging things this way would not allow for, say, attempting application level rollback or things like that.

    I don't think it would make a ton of sense to set this up on every state object, which is also harder to do because I would have to remember to add something to every user command.

One could make a factory function for that, or a decorator (already available in TS, coming to a next JS release). It would be less efficient since you'd set this on every object, but it would make it easier to work out edge cases if needed.

**Comment by ronkorving** [comment]
I think the default should be easy and useful, out of the box. I'm getting the impression you may not have understood my proposal well enough. `State` objects carry a `data` object around. You could easily set `state.data.retries = 0;` (or whatever logic you may fancy) if you didn't want any retries on this state. When the `mage.core.archivist` error handler gets called, it could inspect that on the state that is passed and act on it.

**Comment by stelcheck** [comment]
I believe we have different assumptions: I assume that when retries will be used, it will be the exception, not the rule. And that recovery logic might also be different on a case-by-case basis.

**Comment by stelcheck** [comment]
Closing due to lack of interest. Please re-open if still deemed relevant.
