### ISSUE TITLE
A default TTL (expiration time) for topics

### ISSUE THREAD

**Issue by ronkorving** [mage/mage#163]
We could add a default TTL (number and maybe even function) to topic/vault in lib/archivist/index.js, I think that would be very useful for cache lifetime management (configure it once, not for every `set()` call) and it can even replace the responseCache configuration completely.

Thoughts?

**Comment by stelcheck** [comment]
I think that could help avoid some classes of bugs where data is expected to expire but doesn't. In general, instances of a given type are likely to all be persistent or ephemeral.

**Comment by stelcheck** [comment]
@ronkorving could you PR this one in if you want to see this happen?

**Comment by ronkorving** [comment]
No problem. Allow me some time though.

**Comment by stelcheck** [comment]
Sure. Can you provide me with a ballpark ETA?

**Comment by ronkorving** [comment]
I think I may be swamped until the end of January. So it's kind of hard to give an ETA on this at this time, except to say it will not be very soon.

**Comment by stelcheck** [comment]
Could you provide a tentative date somewhere in February then? I don't mind to see the date change later, but I want to make sure to know when to revive this issue should it remain unaddressed.

**Comment by ronkorving** [comment]
Let's say I'll work on it around Feb. 15 👍

**Comment by stelcheck** [comment]
Understood. If anyone seeing this feels like joining in, feel free to do so.
