### ISSUE TITLE
can i use complex sql in mysql Vault

### ISSUE THREAD

**Issue by hello2dj** [mage/mage#203]

**Comment by ronkorving** [comment]
Hi,

You can, if you access `myVault.pool`. This is a [node-mysql pool](https://www.npmjs.com/package/mysql#pooling-connections) instance, so you have access to all node-mysql features.

Keep in mind though that archivist queues up data mutations and does not execute any mutation if a logic-error prevents your user command from completing successfully. All this behavior will not apply when you use the pool directly. You are at this point no longer going through MAGE, or archivist.

**Comment by hello2dj** [comment]
thank you

**Comment by ronkorving** [comment]
Good luck 👍  Assuming this is resolved, I will close this issue. Please do not hesitate to write back if you have any further questions.

**Comment by hello2dj** [comment]
yes, so warm
