### ISSUE TITLE
Relative clientHost expose URL with a different port

### ISSUE THREAD

**Issue by ronkorving** [mage/mage#214]
On the project I'm currently working on, we are serving our assets (all HTML, CSS, JS) with `webpack-dev-server` on port `8080`. The MAGE server is listening on port `8081`. Therefore, we need to configure an `expose` URL:

```yaml
server:
    clientHost:
        expose: "http://127.0.0.1:8081/"
```

The problem with using `127.0.0.1` prevents me from connecting from any other machine. I don't want to configure another local IP, because it changes and is different for all developers on the team. So what I really want is a relative URL, but with a specific port. I don't know of any valid way to write that though. These are not valid URL definitions:

- `http://:8081/`
- `//:8081/`

As far as I have been able to find out, you cannot specify a port without a host name.

The way I test/confirm validity is using the DOM `URL` API:

```js
new URL('//:1234', window.location.href); // throws
```

**Proposal:**

I propose a special notation that allows a host name `*` to be replaced with the current host name (`window.location.hostname`) by client SDK when it reads `mageConfig`. I have already tested this to do the job for us in a workaround fashion:

```yaml
server:
    clientHost:
        expose: "http://*:8081/"
```

```js
window.mageConfig.server.baseUrl = window.mageConfig.server.baseUrl.replace('*', window.location.hostname);
window.mageConfig.server.commandCenter.url = window.mageConfig.server.commandCenter.url.replace('*', window.location.hostname);
```

Super nasty workaround to do it this way, but it proves the point. If MAGE supported this out of the box, I think that would be very helpful.

Feedback welcome. Does anyone see other solutions that are as user-friendly?

**Comment by stelcheck** [comment]
That would indeed be useful, but how about allowing configuration overrides in the client instead? This would have the advantage of:

  1. Requiring no additional notations
  2. Remain entirely server-independent

Example:

> client code

```javascript
const MageSdk = require('mage-sdk-js/config')
const endpoint = new URL('//:1234', window.location.href)

MageSdk.configure(mageConfig)
MageSdk.setEndpoint(endpoint)

const mage = MageSdk.connect() // same as require('mage-sdk-js')

// Require additional modules here
```

> https://github.com/mage/mage-sdk-js/blob/master/config.js

```javascript
exports.configure = (config) => {
  const top = typeof window === 'undefined' ? global : window;
  top.config = config 
}

exports.setEndpoint(url, app = '/game', msgstream = '/msgstream' savvy = '/savvy') {
    const { server } = this.config
    server.baseUrl = `${url}`
    server.commandCenter.url = `${url}${app}`
    server.savvy.url = `${url}/${savvy}`

    const { transports } = server.msgStream
    for (const transport of Object.values(transports)) {
      transport.url = `${server}${msgstream}`
    }

    exports.configure(this.config)
}

exports.connect = () => require('./')
```

The actual code would need to do some additional check, but, it would provide a very flexible and extensible API for dealing with runtime configuration.

**Comment by havill** [comment]
Quick comments by someone who is very late to the game:

1. The (convention... ex. Vagrant and Jeckel) normal convention for a wildcard host (that listens on every network interface) is to use the bogus IPv4 address "0.0.0.0". This way the parser for whatever service that may take a URL besides the one we're talking about here (MAGE) is less likely to break on a bogus ("http://*/") URL.
2. Might be a good idea to separate out the scheme (http/http) host, port, and path into separate fields, and pass them individually or as a wrapped up struct/object. Servers such as Apache do this for configuring what ports/virtual & physical hosts,  and ports... to allow for this sort of flexibility.

As for the debate as to whether to do this on the server or the client for MAGE, I'll defer on commenting as I don't know enough about it yet.

**Comment by ronkorving** [comment]
@havill 
Your 2nd suggestion is actually how this used to be configured. But since it all fits perfectly fine (except *this* case) in a parseable URL, that was just way too much hassle. Also, the behavior of properties overriding other properties between config files makes that a little bit too granular imho.

With regards to using the asterisk, it's a convention I picked up from ZeroMQ, where they use it as well. The use-case for ZMQ is not the same as ours here, but then again, the same can be said for `0.0.0.0`.

**Comment by havill** [comment]
After communicating with Labey re the old current and new SDK, it seems that the solution to this (export one/multiple client urls/endpoint) is to set the server endpoint, and the SDK will fetch the client config from the server (which exposes it via an user command). To see the difference in usage between the 2 versions, you can refer to the repositories readme:

- [current version](https://github.com/mage/mage-sdk-js/tree/master/docs)
- [new version](https://github.com/Nokitoo/mage-sdk-js/tree/features/get-config/docs)

The [Unity SDK](https://github.com/mage/mage-sdk-unity) does not load the client config.

Because we changed how the client config is loaded into the SDK, and it's not the responsibility of the SDK anymore, I don't think this issue is relevant anymore, and I'll close it.
