### ISSUE TITLE
Handle Couchbase errors

### ISSUE THREAD

**Issue by Nokitoo** [mage/mage#221]
I think we could add better Couchbase errors handling.

For example, if I don't have any Couchbase server running, the only error I have is "{code: 16}", and I only receive it while trying to do an operation, and not on server start up.

I propose these following fixes:
- Call the [initialization part](https://github.com/mage/mage/blob/master/lib/archivist/vaults/couchbase/index.js#L112) in CouchbaseVault.setup rather than on the first operation
- When getting an error, retrieve the [message code meaning](https://developer.couchbase.com/documentation/server/4.6/sdk/nodejs/handling-error-conditions.html)
- Use detailed_errcodes in [client config](https://developer.couchbase.com/documentation/server/5.1/sdk/nodejs/client-settings.html) so we get the error message for better debugging

For the last point, we could add it in the vault config, or enable it by default.
Also, setting detailed_errcodes to 1, does not only add a message error, but can also change the error code. For example, when no Couchbase server is running and detailed_errcodes is not set, I get the error code 16 (networkError) but if I set detailed_errcodes to 1, I get error code 44 (connectionRefused).

What do you think @stelcheck and @christopherobin ?

For CouchbaseVault.get, is there any specific reason for not returning the error in the callback ? ([Here](https://github.com/mage/mage/blob/master/lib/archivist/vaults/couchbase/index.js#L189))

**Comment by stelcheck** [comment]
> Call the initialization part in CouchbaseVault.setup rather than on the first **operation**

Make sense to me *if* that's how all other vaults are to behave from now on (we can change that behavior as we go).

> When getting an error, retrieve the message code meaning

Having both would help. We could simply extract the string key from the error enum and print it alongside the numerical error code.

> For CouchbaseVault.get, is there any specific reason for not returning the error in the callback ?

Not finding a value may or may not be an error; this check is handled higher in the stack, hence why the error is ignored there.
