### ISSUE TITLE
Add modules in documentation

### ISSUE THREAD

**Issue by Nokitoo** [mage/mage#238]
I think it would be nice to list and explain in the documentation all the modules that can be used with mage such as [mage-vaulthelper-couchbase](https://github.com/mage/mage-vaulthelper-couchbase), [mage-console](https://github.com/mage/mage-console) and [mage-validator](https://github.com/mage/mage-validator).

In the same sense, we could also document/list the routes created by the internal modules of mage such as session and time. But I don't know if it would make sense as it seems it's only used internally by the client sdks. What do you think @stelcheck ?

**Comment by stelcheck** [comment]
Sounds good to me. We should probably keep it short, but referring people to those modules would definitely be helpful.
