### ISSUE TITLE
Modify how mage-sdk-js get Mage config

### ISSUE THREAD

**Issue by Nokitoo** [mage/mage#239]
Currently for the mage-sdk-js, we need the client and server to be on the same repository. It's not very convenient and client/server should be separated.

Linked to the proposal in the issue #214, I would make this proposal:

1. **Automatically add a route on server-side to get the "client config"**

When starting the server, it would add a route to get the "client config" the same way we are doing for [httpBatchHandler](https://github.com/mage/mage/blob/master/lib/commandCenter/httpBatchHandler.js#L427).

2. **Modify/Rename `Mage.getClientConfig`**

As client and server should be separated, it may be a great idea to get a config without client `baseUrl`. We should do this in the sdk instead (Like in #214 proposal).
Thus, we could also rename it to `getConfig` or `getServerConfig`.

3. **In the mage-sdk-js, set the baseUrl and automatically get the config**

In the mage-sdk-js, we could just set an endpoint, and the sdk will take care of getting the server config and concatenate server config with `baseUrl`.

We could do something like this:
```javascript
const mageSdk = require('mage-sdk-js');
const endpoint = new URL(window.location.href);
endpoint.port = 1234;

mageSdk.setEndpoint(endpoint.href);

// Get config from server
mageSdk.init();

mageSdk.addModule('session', require('mage-sdk-js.session'));

mageSdk.setup(function(error) {
    // ...
})
 ```

Or: 

```javascript
const MageSdk = require('mage-sdk-js');
const endpoint = new URL(window.location.href);
endpoint.port = 1234;

// Create instance and get config from server
const mageSdk = new MageSdk(endpoint.href);

mageSdk.addModule('session', require('mage-sdk-js.session'));

mageSdk.setup(function(error) {
    // ...
})
 ```

I don't know how works [mage-sdk-unity](https://github.com/mage/mage-sdk-unity), but we could do the same. @stelcheck, how does mage-sdk-unity load Mage config ?

**Comment by stelcheck** [comment]
@AlmirKadric would be better positioned to answer. I don't think it actually uses it IIRC.

**Comment by stelcheck** [comment]
Addendum: `init` would need to be async.

**Comment by Nokitoo** [comment]
Yes, or take a callback to be consistent with the actual sdk.

**Comment by AlmirKadric** [comment]
@Nokitoo short answer: Mage Unity SDK doesn't use the mage config. As C# is typesafe, unless we create some kind of class template generator for all the routes and modules, we don't have much benefit from using the mage config apart from validating if a route actually exists on the client side.

@ronkorving  and I discussed something similar to this quite some time ago. We were planning on rewriting the client configuration system entirely. Unfortunately I wasn't able to find an RFC for this but what we had in mind was similar to what you're suggesting with 1 extra consideration:
 - Client can have an individual configuration for initial URL or will use host it was served from
 - Have a getConfig usercommand as you suggested which is avaialbe by default as part of the sdk
 - Use the getConfig usercommand to setup mage and initially available usercommands for anonymous access level
 - Have the session module recall the getConfig usercommand on session.set to reconfigure available usercommand list for elevated access

hope this helps 👍
