### ISSUE TITLE
Document sharding

### ISSUE THREAD

**Issue by Nokitoo** [mage/mage#240]
We should document how to use sharding with the module [mage-module-shard](https://github.com/mage/mage-module-shard) in the userguide. There is already a documentation in the repository of this module but I find the idea of sharding difficult to grasp.

In the userguide we may explain what is sharding in a more global point of view, and how to implement it with a real use case tutorial in a game.
Or, we could add this in the module repository and wait for issue #238 to be closed to reference the module's repository.

I don't know what's the best idea, as sharding is almost always used so just referencing the repository may not be enough.

**Comment by stelcheck** [comment]
Documentation about sharding should be mage-module-shard. 

I think the best for tutorials and user guide would be to post them on blogs and social media. We have https://medium.com/mage-framework and https://twitter.com/mageframework available to distribute such knowledge; what we would most likely want to do is ensure we link to those in the doc and readme I think.

**Comment by Nokitoo** [comment]
@stelcheck https://medium.com/@glabey

**Comment by stelcheck** [comment]
I'll close this since its not related to mage core.
