### ISSUE TITLE
create project on win10 via npx

### ISSUE THREAD

**Issue by hieutd1** [mage/mage#267]
i got this error when create js project on win10 (x64) via npx
#
> events.js:183
      throw er; // Unhandled 'error' event
      ^
Error: spawn npm ENOENT

I was tried to use npm.cmd instead npm at scripts/create.js@177. And it worked fine.
![image](https://user-images.githubusercontent.com/10185037/48548310-3519fc00-e8ff-11e8-8741-efbd197d4e2a.png)

**Comment by stelcheck** [comment]
Just to confirm, were you using CMD or Powershell as your terminal? IIRC we do not support CMD or git shell on windows.

**Comment by hieutd1** [comment]
I was using powershell, node 8.12

**Comment by stelcheck** [comment]
Are you using a version manager such as NVS, or a direct install?

**Comment by stelcheck** [comment]
https://github.com/mage/mage/blob/master/scripts/create.js#L178 Appears to be the issue - for some reason, it seems NPM could not be found.

**Comment by stelcheck** [comment]
@hieutd1 Apologies for the delay - there is a PR which will be fixing this issue, we'll make a release once it's in.
