### ISSUE TITLE
archivist-create: couchbase oddities

### ISSUE THREAD

**Issue by stelcheck** [mage/mage#27]
If I do not specify a `create` configuration, I get no warning or information on how to configure MAGE so that archivist-create may create the buckets I need:

```plaintext
m-2411 - 10:18:31.449     <debug> [MAGE archivist] Creating persistent vaults ["volatileVault","userVault","queueVault","gameVault"]
m-2411 - 10:18:31.465     <debug> [MAGE archivist vault:volatileVault] Setting up couchbase vault, using flagStyle default
m-2411 - 10:18:31.479     <debug> [MAGE archivist vault:userVault] Setting up couchbase vault, using flagStyle default
m-2411 - 10:18:31.492     <debug> [MAGE archivist vault:queueVault] Setting up couchbase vault, using flagStyle default
m-2411 - 10:18:31.492     <debug> [MAGE archivist vault:gameVault] Setting up couchbase vault, using flagStyle default
m-2411 - 10:18:31.505     <debug> [MAGE] Shutting down Mage...
m-2411 - 10:18:31.507     <debug> [MAGE archivist] Closing all vaults...
m-2411 - 10:18:31.527     <debug> [MAGE] Destroying all log writers
```

**Comment by stelcheck** [comment]
@AlmirKadric would love to get some feedback on this one whenever you have some time.

**Comment by stelcheck** [comment]
@AlmirKadric still waiting for feedback.

**Comment by AlmirKadric** [comment]
That was originally by design, originally couchbase bucket were created manually
However we introduced this create flow for dev and test environments
This being said, now that we are OSS, we should definitely have some indicator saying that the bucket was skipped and they can refer to XYZ link to configure it.

**Comment by stelcheck** [comment]
That sounds good. Would it be too harsh to flat out error out? How should the log output look like in your opinion?

**Comment by AlmirKadric** [comment]
There is already a skipping vault warning when no there is no migration for a given vault
```
m-110820 - 19:30:01.367   <warning> [MAGE migration] No migration folder found for vault volatileVault (skipping).
```
So in a similar light, we should have something like:
```
m-110820 - 19:30:01.367   <warning> [MAGE migration] Couchbase vault <VaultName> is not configured to automatically "create" (skipping) (please check here on how to configure couchbase vaults to automatically create buckets: <URL TO DOCS>).
```
Also this feature should not be used in production so similarly we could have an error which warns if NODE_ENV=production or update the above error message that mentions as such.

**Comment by stelcheck** [comment]
Would you be able to PR this in within a reasonably short amount of time, so to get rid of this issue?

**Comment by stelcheck** [comment]
Ping @AlmirKadric

**Comment by stelcheck** [comment]
As per discussion with @AlmirKadric we will try to get that PR'ed in by August 10.

**Comment by stelcheck** [comment]
Switching assignment to @christopherobin as per discussion.
