### ISSUE TITLE
new project template: "main" field in package.json

### ISSUE THREAD

**Issue by ronkorving** [mage/mage#34]
With a "main" field that would point at "lib/index.js", users would be free to change this path after the fact, while at the same time being able to run `npm run develop`. That is, `bin/mage` would be able to `require(process.cwd())` instead of `process.cwd() + '/lib'`.

**Comment by stelcheck** [comment]
Are you sure this works? I tried quickly and got an error like this:

```shell
Error: Cannot find module '/Users/mt/Sources/mage-parser/test/fake-project'
```

`package.json` contains `"main": "./lib/index.js",`

**Comment by stelcheck** [comment]
Whoops, sorry I closed it by mistake.
