### ISSUE TITLE
Modules require an 'index.js'

### ISSUE THREAD

**Issue by stelcheck** [mage/mage#35]
I may have a module composed only of usercommands; in which case, creating an empty index.js at the top level of the module seems to be a bit of a waste.

**Comment by ronkorving** [comment]
I wouldn't consider this a bug, it's quite by design. But it can be considered inconsistent with the Web SDK which doesn't exist on JavaScript file existing. It's perfectly happy with user commands only.

**Comment by stelcheck** [comment]
TBH it's mostly for development and testing; sometimes I just want to create user commands quickly, without having to create an `index.js` with nothing in it.
