### ISSUE TITLE
What to do about Plato?

### ISSUE THREAD

**Issue by ronkorving** [mage/mage#4]
Right now we use the `yaml2json` dependency for Plato, which seems overkill. Plato should be able to pass a yaml config file to ESLint. If it can't, let's fix Plato.

We also have `yamljs` lingering around, and it seems we should not need it.

If we can get rid of them, that would be nice. But these are dev dependencies only and don't have any negative impact (beyond dev installations being a tiny bit slower), so it's not a massive priority.

**Comment by ronkorving** [comment]
So it turns out Plato is really not maintained anymore. We need to look for something else. I haven't been able to find anything as good as Plato though. The big question is: do we keep using Plato in the mean time?

**Comment by ronkorving** [comment]
`yamljs` exposes a "binary" that we use to convert our eslint configuration to JSON.

**Comment by stelcheck** [comment]
https://bjoernkw.com/2016/11/27/jscity-code-complexity-visualization-for-javascript-codebases/

**Comment by ronkorving** [comment]
That takes about a day to render the scene on my laptop, using the example on that page. Then I found these examples which are a lot faster: https://github.com/ASERG-UFMG/JSCity/wiki/JSCITY

But this doesn't give very useful metrics, like Plato did.

**Comment by stelcheck** [comment]
Then I'd say flat out remove Plato. I doubt anyone uses it anyway at this point.

**Comment by stelcheck** [comment]
Dug a bit deeper.

So the most useful thing I think we could do at this point is indeed remove Plato. However, I also found this tool

https://vile.io/#features

Which in turns has a plugin for escomplex: https://www.npmjs.com/package/vile-escomplex

We would need to test it, but while we'd loose the capability of producing local reports, we'd gain the capability of visualizing them online - that, and, if I get this right, visualizing how complexity is evolving as well.

**Comment by stelcheck** [comment]
Assigning the both of us to this task - I'll make sure to look a little deeper into vile.io, and of course would love to get your feedback on it as well.

**Comment by ronkorving** [comment]
Vile actually looks very promising 👍

**Comment by stelcheck** [comment]
https://vile.io/~stelcheck/mage

Just gave it a try. to be honest, the reports and graph don't seem all that useful in the end, so I would consider having a look at other alternatives.

**Comment by ronkorving** [comment]
I get a 404 on that URL

**Comment by stelcheck** [comment]
Did you try to create an account and log in? It's supposed to be public, but maybe public means "logged in on their platform"?

**Comment by ronkorving** [comment]
Even after logging in, 404.

**Comment by stelcheck** [comment]
This subject isn't going anywhere, and we couldn't come up with any actionables so far. 

Would suggest closing this issue until we have a proper solution or alternative. Plato isn't hurting anyone at the moment. Either that, or we remove Plato (I personally do not use it).

**Comment by ronkorving** [comment]
Let's remove it. One less dependency to keep track of.
