### ISSUE TITLE
zookeeper: connection lost

### ISSUE THREAD

**Issue by stelcheck** [mage/mage#52]
```plaintext
m-42 - 13:14:46.113     <alert> [MAGE msgServer] Exception: CONNECTION_LOSS[-4]
  data: {
    "code": -4,
    "name": "CONNECTION_LOSS",
    "file": "ConnectionManager.js",
    "line": 720,
    "offset": 28,
    "type": "CONNECTION_LOSS",
    "stack": [
      "ConnectionManager.queue (node_modules/node-zookeeper-client/lib/ConnectionManager.js:720:28)",
      "node_modules/node-zookeeper-client/index.js:799:36",
      "async.whilst.args (node_modules/node-zookeeper-client/index.js:125:13)",
      "Object.async.whilst (node_modules/node-zookeeper-client/node_modules/async/lib/async.js:619:13)",
      "Timeout._onTimeout (node_modules/node-zookeeper-client/node_modules/async/lib/async.js:623:23)",
      "ontimeout (timers.js:386:14)",
      "tryOnTimeout (timers.js:250:5)",
      "Timer.listOnTimeout (timers.js:214:5)"
    ]
  }
```

I do not know if its an issue, but I did not see any logs pertaining to reconnect attempts following that. This would mean that some clustering issues would likely occur under adverse network conditions.

Assigning @ronkorving and myself to investigate whether 1. There is a reconnect attempt, and 2. What is the reconnect logic, and 3. Make sure that a `notice` log level is emitted for both zookeeper disconnect and reconnect.

**Comment by stelcheck** [comment]
@christopherobin can you confirm whether this would be an issue?

**Comment by stelcheck** [comment]
@ronkorving @AlmirKadric @christopherobin any ideas if this would be an issue? I have only experienced this in development (when bringing back my PC from sleep mode), but if that were to happen in production I fear the MAGE server would simply be taken out and the cluster would end up in a split-brain.

**Comment by ronkorving** [comment]
I imagine it could be an issue. When our zookeeper engine emits error events (which msgServer logs), *it* does not retry anything. Maybe the node-zookeeper-client does though.

**Comment by stelcheck** [comment]
This is then a rather serious issue. Any connectivity issue would then lead to a split brain in the mmrp cluster at the very least. Players on a given server will stop receiving messages and won't be able to send any either.
