### ISSUE TITLE
readme/user doc: feature list (why mage?)

### ISSUE THREAD

**Issue by stelcheck** [mage/mage#55]
@Tatsujinichi pointed out that while we do have some user documentation, one crucial element is missing: basic feature list.

I suggest that we deal with this in the following fashion:

  1. Add a short list to the Readme
  2. Link from the Readme to the user documentation; create a "features" list, and for each bullet in the Readme list, create a small sub-paragraph describing it (and linking to relevant user and API documentation portions)

Current list I have in mind is:

  - Transactional API endpoints
  - Message passing through event emission
  - Abstracted storage backend
  - Built-in clustering
  - Production ready logging and metrics APIs
  - TypeScript support
  - Multiple client SDKs and libraries
  - Ecosystem of external tools and libraries (mage-console, mage-validator, etc)
  
@ronkorving @AlmirKadric I find the list a tad long already, but am I forgetting anything important? Or perhaps anything we could remove from this list?

**Comment by Tatsujinichi** [comment]
@stelcheck Thanks!
I was looking for:
What I can do with Mage? What problems do I have that Mage solves?
And for each solution that fits my problem, a minimalistic step by step example. 
For example; I come along with a problem, I look at the feature list to see if mage has a solution to my problem.  If it does, I look a step deeper to learn how to utilize this specific feature.  Kind of like a path, from problem to solution, with as little noise as possible.

**Comment by AlmirKadric** [comment]
The only thing that you don't have, although you could argue isn't all that important, is sessions and identification management. Other than that 👍
