### ISSUE TITLE
Bootstrap creates filevaults for auth not in gitignore

### ISSUE THREAD

**Issue by nullorvoid** [mage/mage#58]
Noticed this when about to push a small sample project, the gitignore doesn't include the file vaults.  After a conversation with @ronkorving it might not be appropriate to create the auth module and such in the bootstrap.

I'm on the side that creating these is actually a good thing, but it might take the user down the path where they use filevault for everything, like auth and such, which probably isn't so good.

@stelcheck what is your opinion on this? How do you think we should go about it.

**Comment by stelcheck** [comment]
We could remove the auth module from the bootstrap, and that would be the end of it... but.

While technically, you can create an app with no auth whatsoever and make it work, you will normally at least need to log players anonymously. So the first thing you will need to do is to add the module, and then add the topic - and topics require storage backends.

Now, if you store to disk, in most cases I have seen in the past the data needed to go in git - that is why I think the filevault is not ignored.

With that in mind, I see only two options:

  1. Store to disk
  2. Store in memory

For a bootstrapped project, I think the second option would be interesting; it still allows for hands-on testing in a freshly created playground project, and all you need to do to clean everything up is restart the server. 

However, should we go in that direction, we'd clearly need to have log outputs showing that you are using a vault that actually doesn't store anything. If the auth module could do that, and point in the log output to proper documentation about how to change the vault backend and configure it, then I think we'd have something that quite easy to play with for developers.

Additional thoughts and suggestions welcome.

**Comment by stelcheck** [comment]
Pinging this issue. Is everyone happy with my suggestion?

**Comment by ronkorving** [comment]
The nicest thing about filevault for dynamic data though goes away with using memory vault:

The ability to very easily inspect your data set. With file vault it's all in nicely serialized .json files. That makes for a very nice way to visually test and confirm that things are being persisted as you intended it.

**Comment by stelcheck** [comment]
With mage-console, that's no longer entirely true, however.

**Comment by ronkorving** [comment]
How so? Because you can use archivist API? Because that's still nowhere close to having a nice directory full of .json files to browse through.

**Comment by stelcheck** [comment]
You can simply use mage in the REPL to query your data.

**Comment by ronkorving** [comment]
Yeah, but like I said, that really doesn't come close.

**Comment by stelcheck** [comment]
Ok, lets take a step back. How about we added a feature in the bootstrap to select the vault backend? This would at least hint to developers that there is a choice. We could also skip creating filevault required files in cases where we don't need them.

**Comment by ronkorving** [comment]
Let's take one more step back. @nullorvoid's concern was this:

> I'm on the side that creating these is actually a good thing, but it might take the user down the path where they use filevault for everything, like auth and such, which probably isn't so good.

That problem is no less when using a memory vault. We don't want users to assume that either memory vault or file vault are useful defaults for production, because neither is.

So making the user choose between memory and files doesn't solve the issue that was raised I think. So I think the question is:

> How do we communicate to the user that using the file vault for user data is only useful as a development experience?

Or am I getting this wrong, @nullorvoid ?

**Comment by stelcheck** [comment]
> That problem is no less when using a memory vault. We don't want users to assume that either memory vault or file vault are useful defaults for production, because neither is.

Hence my suggestion of making this configurable during bootstrap. By that, I mean choosing between all supported vaults, not only filevault or memory.

This being said, the default would still likely be filevault, and I agree we should probably warn against its use - however, outside of documentation, I hardly see where this would be appropriate. And we are back to square 1. 

So coming back to my suggestion: if we could make the vault backend selectable, and then on-screen quickly list when using such and such vault make sense, I believe we may have a chance to crack this one up, and provide a better end-developer experience.

**Comment by ronkorving** [comment]
After having discussed face-to-face with @stelcheck, we've come to the agreement that the end-goal should be a friendly UX that can guide you to set up *any* vault type for (in this case) auth. It is here that we could inform the user about the ups and downs of using file vault. We acknowledge however that a system like this won't happen any time soon.

Also in the longer term, I would like to externalize the auth module (all modules for that matter), and it may be smart to do so before introducing a system like that. Time will tell.

A fair approach for now may be to either remove auth from the enabled-by-default list of modules. This forces users to go through the manual when setting it up, which is where we can give an appropriate warning about how to use vaults.

Any other suggestions welcome, @nullorvoid. But this is really the only path we could really agree on so far.

**Comment by stelcheck** [comment]
@nullorvoid Waiting for your feedback.

**Comment by stelcheck** [comment]
@christopherobin Temporary assigning you to this task - could you please follow-up with everyone on this thread, and see how we could solve this issue?

**Comment by nullorvoid** [comment]
@ronkorving @stelcheck  I think this slightly went sideways

The problem I had was that my auth credentials were about to be pushed to source control with the bootstrap.

My secondary concern with any proposed solution was that:
> I'm on the side that creating these is actually a good thing, but it might take the user down the path where they use filevault for everything, like auth and such, which probably isn't so good.

So @stelcheck comments addressed my first and primary concern which was that the auth vault was created and would be committed by anyone not knowing fully about Mage. And @ronkorving addressed the secondary concern with needing to have much better feedback about the datastores.

However also the fact that filevaults are used for static data and things you want to commit to github. In this case can we not just add the userVault specifically to the gitignore?

**Comment by stelcheck** [comment]
We could, but I don't think it really solves the core issue, which is that you should never use file vault for credentials. It's a really bad match for 95% of the cases, the other 5% being "I want to test MAGE with a throwaway project" - and even in *those* cases, why even bother with auth? 

This is why we (@ronkorving and I) came to the conclusion that removing auth and asking developers to add it manually once needed.

**Comment by nullorvoid** [comment]
ok

**Comment by Tatsujinichi** [comment]
behold!
https://github.com/Wizcorp/go-mage/tree/develop/filevault/userVault
