### ISSUE TITLE
config: enforce configuration values programmatically 

### ISSUE THREAD

**Issue by stelcheck** [mage/mage#67]
For testing purposes, I would like to make sure to programmatically disable certain modules such as serviceDiscovery and MMRP - instead of having to enforce the use of an environment variable for running tests. 

@ronkorving @qubyte help/pointers on how I could get this done would be most welcome.

**Comment by qubyte** [comment]
I'll have to refresh myself on how how mage modules work again before I have much useful to say. However, for regular node modules I'm a big fan of sinon for stubbing the exports of object-like modules, and sandboxed-module (much heavier) for function-like modules.

Regardless of how mage modules work, the latter solution will always work, but since it means loading modules from scratch each time it is used, it usually entails careful use of `before` when writing tests to avoid loading everything for every test.

**Comment by stelcheck** [comment]
The main issue is that right now, the configuration is loaded as soon as we require MAGE; this means that there are no ways to programmatically disable those two modules since they basically get set up right after configuration in the current code path:

https://github.com/mage/mage/blob/master/lib/mage/Mage.js#L241

**Comment by qubyte** [comment]
Yup, sandboxed-module can rescue you from this case by allowing you to stub config. Something like

```javascript
let Mage;

before(() => {
    Mage = SandboxedModule.require('../path/to/Mage', {
        requires: {
            '../config': {
                // replacement config here
            },
            // stub other modules if needed
        }
    });
});
```

The cost is that you're loading a fresh instance of that Mage module in a sandboxed environment. 

A better way might be to have config required higher up in the app, and fed in as an argument to a setup function. Tests would then require in the pre-setup Mage and call the setup function with whatever config they like. Naïvely I'd alter `setupCoreLibs` to take config as an argument. That would alter `./lib/mage/index.js` to look like:

```javascript

/** @module mage */

const config = require('../config');
const Mage = require('./Mage');

// Make a mage instance with the loaded configuration, and assign it as the module.exports.

const mage = module.exports = new Mage(module);
mage.setupCoreLibs(config);

// Global default settings override.

require('http').Agent.defaultMaxSockets = 100;	// max 100 parallel client sockets per agent
```

In tests you would now require and manipulate `mage/Mage` directly, avoiding `mage/index` and baked in config.

**Comment by stelcheck** [comment]
@ronkorving what do you think? Seems that would require tangible changes... nevertheless, it would be rather useful, for testing if anything.

**Comment by ronkorving** [comment]
I'm a big fan of feeding configuration from the outside, and not have modules read their own. It would be a significant change though, but in the long run, I'm in favor.

**Comment by stelcheck** [comment]
Actually, we could just add a `set` method on the config, and require it prior to requiring  MAGE. Let me try to have a crack at this.
