### ISSUE TITLE
Superfluous slashes in an URL should be processed properly

### ISSUE THREAD

**Issue by stelcheck** [mage/mage#74]
Example:  

  * https://localhost:8080/game/player.login
  * https://localhost:8080/game//player.login
  * https://localhost:8080//game/player.login

Should all resolve to the same usercommand - at the moment, the last two ones would give you a 404.

@AlmirKadric @ronkorving

**Comment by ronkorving** [comment]
Do you know by any chance how other servers deal with this? Do they:

a. internally rewrite the URL and handle it
b. send a redirect message to the client (like how most web servers deal with a missing `/` at the end of a URL that is supposed to point to a folder, not a file)

**Comment by stelcheck** [comment]
GitHub pages just leave it as is; in our case, this should be fine too.

Sending a redirect would potentially introduce performance issues in consuming clients, so for me, that would be a no-go.

**Comment by ronkorving** [comment]
As I said, that already happens for missing trailing slashes to the best of my knowledge, so it's not an uncommon solution. I would rather follow common patterns, than trying to optimize HTTP behavior in our own creative ways ;) But again, if that is the common approach (dealing with it server-side), I'm fine with that.

**Comment by stelcheck** [comment]
See https://github.com/mage/mage/issues/74////////////////////////////
