### ISSUE TITLE
logger data: passing an array outputs incorrect data

### ISSUE THREAD

**Issue by stelcheck** [mage/mage#96]
Given:

```javscript
const logger = mage.logger.context('send')
logger.debug.data(presents).log('presents')
logger.debug(presents[0].userId)
```

The output is:

```plaintext
w-3319 - 01:12:50.622     <debug> [app send] send presents
  data: [
    []
  ]
w-3319 - 01:12:50.632     <debug> [app send] aa5249c7-8c84-45aa-abe1-b3450b01770b
```

I expect that other non-object literals would also cause similar issues (although I have not tested).

I see only two options to solve this issue:

  1. Warn or error out on non-objects; this is not too ideal, since some logs may seldom pop up (so you would only figure out that there is an issue in the worst cases)
  2. Assign a label to it automatically (although I am not sure what that label should be)

@AlmirKadric @ronkorving let me know what you guys think

**Comment by ronkorving** [comment]
`data` has 2 ways of being used:

```js
data(key, value);
data(object);
```

It was never designed to take anything but an object in a single-argument call. But you make a compelling argument. Some logs rarely show up, and especially in those, we really want that data. So an automatic `value` label or something wouldn't hurt I guess. I'm for suggestion 2.

**Comment by stelcheck** [comment]
How about we did this for all data calls? 

Take this:

```javascript
mage.logger.debug.data({ a: 1 }).data({ a: 2 }).log()
```

Right now, this is an override.... which might lead to very strange data logs.

What we could do, instead, is log each object separately. Labels could remain optional.

```shell
mage.logger.debug.data({ a: 1 }).data({ a: 2 }).log()
w-20280 - 15:33:49.653     <debug> [mage-testproject-sharding] undefined
  data: {
    "a": 1
  }
  data: {
    "a": 2
  }
```

```shell
mage.logger.debug.data('objectOne', { a: 1 }).data('objectTwo', { a: 2 }).log()
w-20280 - 15:33:49.653     <debug> [mage-testproject-sharding] undefined
  data: {
    "a": 1
  }
  data: {
    "a": 2
  }
```

**Comment by ronkorving** [comment]
How will this integrate with key/value meta data allowing logging services? They don't tend to allow arrays of key/value dictionaries. Just a single one.

**Comment by stelcheck** [comment]
Please refer to the PR implementation for details.
